# Generated by Django 3.0.5 on 2020-04-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0003_auto_20200427_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=15, unique=True)),
                ('roll_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att_app.Class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'students',
            },
        ),
    ]
