# Generated by Django 3.0.5 on 2020-04-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0004_auto_20200427_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
                ('lec1', models.CharField(max_length=50)),
                ('lec2', models.CharField(max_length=50)),
                ('lec3', models.CharField(max_length=50)),
                ('lec4', models.CharField(max_length=50)),
                ('lec5', models.CharField(max_length=50)),
                ('lec6', models.CharField(max_length=50)),
                ('lec7', models.CharField(max_length=50)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att_app.day')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
            },
        ),
    ]
