# Generated by Django 3.0.5 on 2020-04-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0005_day_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='classandsub',
            name='total_lectures',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
