# Generated by Django 3.0.5 on 2020-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0011_auto_20200430_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
