# Generated by Django 3.0.5 on 2020-04-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0012_auto_20200430_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Timetable', 'verbose_name_plural': 'Timetable'},
        ),
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='att_app.student'),
        ),
    ]
