# Generated by Django 3.0.5 on 2020-04-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0013_auto_20200430_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att_app.student'),
        ),
    ]
