# Generated by Django 3.0.5 on 2020-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0014_auto_20200430_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='lec1',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='lec2',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='lec3',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='lec4',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='lec5',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='lec6',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='lec7',
            field=models.CharField(blank=True, default='Blank', max_length=30),
        ),
    ]
