# Generated by Django 3.0.5 on 2020-04-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0015_auto_20200430_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Lab7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='Lab8',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
