# Generated by Django 3.0.5 on 2020-05-01 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0016_auto_20200501_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='att_app.Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='day',
        ),
    ]
