# Generated by Django 3.0.5 on 2020-05-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0017_auto_20200501_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('teacher_teaching', models.CharField(max_length=50)),
                ('total_lectures', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='theorysubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('teacher_teaching', models.CharField(max_length=50)),
                ('total_lectures', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab1',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab2',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab3',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab4',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab5',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab6',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab7',
        ),
        migrations.RemoveField(
            model_name='class',
            name='Lab8',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject1_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject2_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject3',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject3_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject4',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject4_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject5',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject5_code',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject6',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subject6_code',
        ),
        migrations.DeleteModel(
            name='classandsub',
        ),
        migrations.AddField(
            model_name='theorysubjects',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att_app.Class'),
        ),
        migrations.AddField(
            model_name='labs',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att_app.Class'),
        ),
    ]
