# Generated by Django 3.0.5 on 2020-05-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0019_auto_20200503_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='labs',
            new_name='lab',
        ),
        migrations.RenameModel(
            old_name='theorysubjects',
            new_name='theorysubject',
        ),
    ]
