# Generated by Django 3.0.5 on 2020-05-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_app', '0020_auto_20200503_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='Class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='att_app.Class'),
            preserve_default=False,
        ),
    ]
